// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWb9DaXtQG4uH0Iv8UuI8fAHKqdkVRIuQ',
    appId: '1:580619104529:web:e2f24eabc74b3b1b155cb0',
    messagingSenderId: '580619104529',
    projectId: 'tamenny-app',
    authDomain: 'tamenny-app.firebaseapp.com',
    storageBucket: 'tamenny-app.firebasestorage.app',
    measurementId: 'G-8W3JWX5HKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEt_G0vs5kEclxwsIXpid5erqkqkMgth0',
    appId: '1:580619104529:android:bbc05034c71032f2155cb0',
    messagingSenderId: '580619104529',
    projectId: 'tamenny-app',
    storageBucket: 'tamenny-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXpMwWrTmXVvgPqW-49WNh9iXLl9yBwI',
    appId: '1:580619104529:ios:40ea5b02aa2e2f63155cb0',
    messagingSenderId: '580619104529',
    projectId: 'tamenny-app',
    storageBucket: 'tamenny-app.firebasestorage.app',
    iosBundleId: 'com.example.tamennyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXpMwWrTmXVvgPqW-49WNh9iXLl9yBwI',
    appId: '1:580619104529:ios:40ea5b02aa2e2f63155cb0',
    messagingSenderId: '580619104529',
    projectId: 'tamenny-app',
    storageBucket: 'tamenny-app.firebasestorage.app',
    iosBundleId: 'com.example.tamennyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWb9DaXtQG4uH0Iv8UuI8fAHKqdkVRIuQ',
    appId: '1:580619104529:web:12a6653a14622cb5155cb0',
    messagingSenderId: '580619104529',
    projectId: 'tamenny-app',
    authDomain: 'tamenny-app.firebaseapp.com',
    storageBucket: 'tamenny-app.firebasestorage.app',
    measurementId: 'G-2B9Z5RM4BQ',
  );
}
